service: ls-lambda-404

plugins:
  - serverless-localstack

provider:
  name: aws
  runtime: nodejs14.x
  stage: local
  region: eu-west-1
  memorySize: 512
  timeout: 120
  lambdaHashingVersion: 20201221
  

functions:
  routes:
    handler: src/handler.run
    timeout: 28 
    events:
      - httpApi:
          method: 'any'
          path: '/{proxy+}'

custom:
  localstack:
    debug: true
    stages:
      - local
    lambda:
      mountCode: true
    docker:
      sudo: true
  